# Max pooling in Convolutional neural network

In [92]:
import torch
import torch.nn as nn

input_order = 4
image = torch.rand(1, 1, input_order, input_order)

print(image)

tensor([[[[0.5199, 0.1963, 0.8525, 0.3982],
          [0.6666, 0.5388, 0.4454, 0.2653],
          [0.8108, 0.0827, 0.1747, 0.8090],
          [0.8149, 0.1440, 0.1119, 0.2431]]]])


## Max pooling with kernel=2 and stride=1

In [93]:
max_pool_stride1 = nn.MaxPool2d(kernel_size=2, stride=1)
pooled_stride1 = max_pool_stride1(image)
print(pooled_stride1)

tensor([[[[0.6666, 0.8525, 0.8525],
          [0.8108, 0.5388, 0.8090],
          [0.8149, 0.1747, 0.8090]]]])


## Max pooling with kernel=2 and stride=2

In [94]:
max_pool_stride2 = nn.MaxPool2d(kernel_size=2, stride=2)
pooled_stride2 = max_pool_stride2(image)
print(pooled_stride2)

tensor([[[[0.6666, 0.8525],
          [0.8149, 0.8090]]]])


## Convolution without max pooling

In [95]:
cnn = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3)

sobel_filter = torch.tensor([
    [1.0, 0, -1.0],
    [2.0, 0, -2.0],
    [1.0, 0, -1.0]
])
bias = 0.0

cnn.state_dict()['weight'][0][0] = sobel_filter
cnn.state_dict()['bias'][0] = bias

z = cnn(image)
print(z)

tensor([[[[ 0.7459, -0.3812],
          [ 2.1965, -1.2781]]]], grad_fn=<ConvolutionBackward0>)


## ReLu

In [96]:
import torch.nn.functional as F

A = F.relu(z)
print(A)

tensor([[[[0.7459, 0.0000],
          [2.1965, 0.0000]]]], grad_fn=<ReluBackward0>)


## Max pooling with kernel=2 and stride=1 for the convolution done before

In [97]:
print("Conv2d:", cnn.state_dict(), "\n", sep="\n")
print("Convolution result:", z, "\n", sep="\n")

max_pool_stride1 = nn.MaxPool2d(kernel_size=2, stride=1)

z_max_pool_stride1 = max_pool_stride1(z)
print("Max pooling:", z_max_pool_stride1, sep="\n")

Conv2d:
OrderedDict({'weight': tensor([[[[ 1.,  0., -1.],
          [ 2.,  0., -2.],
          [ 1.,  0., -1.]]]]), 'bias': tensor([0.])})


Convolution result:
tensor([[[[ 0.7459, -0.3812],
          [ 2.1965, -1.2781]]]], grad_fn=<ConvolutionBackward0>)


Max pooling:
tensor([[[[2.1965]]]], grad_fn=<MaxPool2DWithIndicesBackward0>)


## Average pooling with kernel=2 and stride=1 for the convolution done before

In [98]:
print("Conv2d:", cnn.state_dict(), "\n", sep="\n")
print("Convolution result:", z, "\n", sep="\n")

avg_pool_stride1 = nn.AvgPool2d(kernel_size=2, stride=1)

z_avg_pool_stride1 = avg_pool_stride1(z)
print("Average pooling:", z_avg_pool_stride1, sep="\n")

Conv2d:
OrderedDict({'weight': tensor([[[[ 1.,  0., -1.],
          [ 2.,  0., -2.],
          [ 1.,  0., -1.]]]]), 'bias': tensor([0.])})


Convolution result:
tensor([[[[ 0.7459, -0.3812],
          [ 2.1965, -1.2781]]]], grad_fn=<ConvolutionBackward0>)


Average pooling:
tensor([[[[0.3208]]]], grad_fn=<AvgPool2DBackward0>)
