# Convolutional neural network

## CNN operator

In [134]:
import torch.nn as nn

cnn = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3)
cnn

Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1))

## Parameters definition

In [135]:
import torch

sobel_filter = torch.tensor([
    [1.0, 0, -1.0],
    [2.0, 0, -2.0],
    [1.0, 0.0, -1.0]
])

cnn.state_dict()["weight"][0][0] = sobel_filter
cnn.state_dict()["bias"][0] = 0.0
print(cnn.state_dict())
print(cnn.stride)

OrderedDict({'weight': tensor([[[[ 1.,  0., -1.],
          [ 2.,  0., -2.],
          [ 1.,  0., -1.]]]]), 'bias': tensor([0.])})
(1, 1)


## Random image (1, 1, 5, 5)

each value is within the range of 0-1

In [136]:
image = torch.rand(1, 1, 5, 5)
print(image)

tensor([[[[0.0818, 0.9518, 0.6388, 0.8855, 0.9175],
          [0.7224, 0.2819, 0.1139, 0.7374, 0.1604],
          [0.3381, 0.4283, 0.3607, 0.1781, 0.5897],
          [0.0199, 0.6454, 0.7889, 0.8135, 0.3800],
          [0.4610, 0.4480, 0.2179, 0.1930, 0.5393]]]])


## Convolution with the default stride

The result has the dimension:
$$n_{new}={n-f}+1$$

- **n** - order of the input tensor
- **f** - order of the filter

In [137]:
z = cnn(image)
print(z)

tensor([[[[ 0.6374, -0.5944, -0.6006],
          [-0.2057, -0.1233, -0.0956],
          [-1.3176,  0.1688,  0.2675]]]], grad_fn=<ConvolutionBackward0>)


## Convolution with the stride=2

stride=2 leads to:
- horizontal move - move 2 values right each time
- vertical mode - move 2 values down after finishing row

The result has the dimension:
$$n_{new}=\dfrac{n-f}{s}+1$$

- **n** - order of the input tensor
- **f** - order of the filter
- **s** - stride

In [138]:
cnn_stride2 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=2)
z_stride2 = cnn_stride2(image)
print(z_stride2)

tensor([[[[0.5372, 0.2895],
          [0.1177, 0.2325]]]], grad_fn=<ConvolutionBackward0>)


## Convolution with the stride=2 and padding=1

The result has the dimension:
$$n_{new}=\dfrac{n+2p-f}{s}+1$$

- **n** - order of the input tensor
- **f** - order of the filter
- **s** - stride
- **p** - padding

In [139]:
cnn_stride2_padding1 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=2)
z_stride2_padding1 = cnn(image)
print(z_stride2_padding1)

tensor([[[[ 0.6374, -0.5944, -0.6006],
          [-0.2057, -0.1233, -0.0956],
          [-1.3176,  0.1688,  0.2675]]]], grad_fn=<ConvolutionBackward0>)


In [140]:
## (P.S.) Padding visualization

In [141]:
import torch.nn.functional as F

padded_image = F.pad(image, (1, 1, 1, 1))  # (left, right, top, bottom)
print(padded_image)

tensor([[[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0818, 0.9518, 0.6388, 0.8855, 0.9175, 0.0000],
          [0.0000, 0.7224, 0.2819, 0.1139, 0.7374, 0.1604, 0.0000],
          [0.0000, 0.3381, 0.4283, 0.3607, 0.1781, 0.5897, 0.0000],
          [0.0000, 0.0199, 0.6454, 0.7889, 0.8135, 0.3800, 0.0000],
          [0.0000, 0.4610, 0.4480, 0.2179, 0.1930, 0.5393, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]]]])
